# Generated by Django 3.2.6 on 2021-09-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210913_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='shop_sizes',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X Large')], default='S', max_length=2, verbose_name='Размеры'),
        ),
    ]
